name: docker-auto-build

on:
  push:
    branches:
      - 'master'
      
# on:
#   push:
#     branches:
#       - "!*"
#     tags:
#       - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy: matrix
    steps:      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Release Tag
        id: tag
        shell: bash
        run: | 
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Test Path
        shell: bash
        run: |
          pwd
          ls -la ../
          ls -la
      - name: Build and push
        id: docker_build
        env:
          TAG: ${{ steps.tag.outputs.tag }}
        uses: docker/build-push-action@v2
        with:
          context: ./clients
          push: true
          tags: maany/gh_action_test_rucio_client:latest