name: docker-auto-build

on:
  push:
    branches:
      - '!*'
    tags:
      - '*'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context_dir: ['clients', 'server', 'daemons']
    steps:      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout the containers repository
        uses: actions/checkout@v2
        
      - name: Get the new Release Tag
        id: tag
        shell: bash
        run: | 
          GIT_TAG=$(echo $(git describe --tags --abbrev=0))
          echo ::set-output name=tag::1.26.1 
          # echo ::set-output name=tag::${GITHUB_REF#refs/*/} 
      
      - name: Debug
        shell: bash
        run: |
          pwd
          ls -la ../
          ls -la
          echo '${{ steps.tag.outputs.tag }}'
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context_dir }}
          push: true
          tags: rucio/rucio-{{ steps.tag.outputs.tag }}:release-{{ steps.tag.outputs.tag }}
          build-args: TAG={{ steps.tag.outputs.tag }}